services:
  web:

    command: uv run python manage.py runserver 0.0.0.0:8000
    image: choozm/docker-django-postgres:latest-dev
    ports:
      - 8000:8000
    env_file:
      - .env.dev

  db:
    image: postgres:18
    volumes:
      - django_postgres_data_dev:/var/lib/postgresql
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  django_postgres_data_dev:

networks:
  default:
    driver: bridge
    name: private_frontend
    external: true